-- MySQL Script generated by MySQL Workbench
-- Thu Sep 29 13:04:48 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `is_admin` TINYINT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`memes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`memes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file` VARCHAR(45) NULL,
  `title` VARCHAR(45) NULL,
  `likes` INT NULL,
  `hash_tags` LONGTEXT NULL,
  `user_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  `categorie_id` INT NOT NULL,
  `created_at` VARCHAR(45) NULL,
  `modified_at` VARCHAR(45) NULL,
  `deleted_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `user_id`, `admin_id`, `categorie_id`),
  INDEX `fk_memes_users1_idx` (`user_id` ASC),
  INDEX `fk_memes_users2_idx` (`admin_id` ASC),
  INDEX `fk_memes_categories1_idx` (`categorie_id` ASC),
  CONSTRAINT `fk_memes_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_memes_users2`
    FOREIGN KEY (`admin_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_memes_categories1`
    FOREIGN KEY (`categorie_id`)
    REFERENCES `mydb`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meme_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `content` LONGTEXT NULL,
  `created_at` VARCHAR(45) NULL,
  `modified_at` VARCHAR(45) NULL,
  `deleted_at` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `meme_id`, `user_id`),
  INDEX `fk_comments_memes_idx` (`meme_id` ASC),
  INDEX `fk_comments_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_comments_memes`
    FOREIGN KEY (`meme_id`)
    REFERENCES `mydb`.`memes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
